apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  name: kiali
spec:
  installation_tag: My Kiali
  istio_namespace: istio-system
  deployment:
    namespace: default
    verbose_mode: '4'
    view_only_mode: false
  external_services:
    grafana:
      url: ''
    prometheus:
      url: ''
    tracing:
      url: ''
  server:
    web_root: /mykiali